name: Python Unit Tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Steup Python
        uses: actions/setup_python@v3
        with:
          python-version: '3.8'
      - name: Run tests
        run: python test_add.py
